# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_remove_doctor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
