# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_doctor_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='company',
        ),
    ]
