# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_remove_doctor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('conditions', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
