# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Patient_list',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
