# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 20:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_auto_20170408_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Patient_list',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
