# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 20:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_auto_20170408_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='conditions',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
