# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 23:21
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_initial_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='Doctor_list',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patient',
            name='conditions',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
